# Generated by Django 4.2.3 on 2023-07-04 08:37

import django.core.validators
from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')])),
                ('date_of_birth', models.DateField(validators=[firstapp.models.Employee.validate_dob])),
                ('date_of_join', models.DateField()),
                ('Address', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=25)),
                ('team', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
