# Generated by Django 4.2.3 on 2023-07-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_employee_created_at_alter_employee_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('name', 'phone')},
        ),
    ]
