# Generated by Django 4.2.3 on 2023-07-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_employee_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_join',
            new_name='doj',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='State',
            new_name='state',
        ),
    ]
